### ISSUE TITLE
ui.bootstrap.collapse animation jumps when padding is added to element to be toggled

### ISSUE THREAD

**Issue by Waterstraal** [angular-ui/bootstrap#3080]
When using the collapse directive on an element that has padding on it, the animation is not smooth but jumps the remaining padded pixels.

I have prepared a plnkr demonstrating the issue: http://plnkr.co/edit/iHZHPYRgGdbouRUyh5xn?p=preview

**Comment by zlincoln** [comment]
+1

**Comment by antoinepairet** [comment]
Thanks for the clear report and the plunkr.
I will mark the issue as an improvement since there is workaround as shown in your plunkr.

The priority is currently set on fixing bugs with angular 1.3 and to officially support it.

**Comment by adriantg** [comment]
I have the same problem... At the moment, I solve this issue replacing the original padding in another div as "container" with this padding. Btw I had to remove the padding.

**Comment by ckahle33** [comment]
@adrxlm  +1. Thanks. Glad it was this simple!

**Comment by mjreddick** [comment]
It should be noted that this is the current behavior in bootstrap as well.  The animation is done on the height (padding is not included in this value) and then when the animation is done the display is set to none and so the remaining padding pixels jump.

http://jsfiddle.net/xkL15guj/2/

**Comment by alexmatveev** [comment]
Just came here to report the same. Current CDN version is the same.

**Comment by adrxlm** [comment]
@chrisirhc 

the @mjreddick  version
http://jsfiddle.net/xkL15guj/2/

My "solution"
http://jsfiddle.net/f5kux78q/1/

**Comment by wesleycho** [comment]
Just noting that this is still an [issue](http://plnkr.co/edit/RnQGp3scFZZhvVwB3Syo?p=preview).

This is likely because the height is set to 0 before the `display: none` style applies, which gives it the jumpy effect. This might be difficult to fix inside collapse itself, but at least there is a good workaround for now.

**Comment by icfantv** [comment]
Closing as this appears to be fixed with the latest version of Angular and Angular UI Bootstrap - 1.4.7 and 0.14.3, respectively.

**Comment by LukasChen** [comment]
@icfantv Why did you close it? the problem still exist: [plunker demo](http://plnkr.co/edit/QqNmEU4lrtF722pNeRJY?p=preview)

**Comment by icfantv** [comment]
@LukasChen, reading my comment from 9 months ago seems to indicate that it was fixed.  It's quite possible that there's been a regression and the bug has returned.  If you believe this to be the case, please feel free to submit a new issue following our issue template which would include a link to a basic plunker showing the issue.

**Comment by chrismooreproductions** [comment]
Bumping this, still a problem in Bootstrap 4 :(

**Comment by Gatunox** [comment]
Yes its a bug

**Comment by peachykeeen** [comment]
Just had this problem. For me it was the combination of padding and height set to an element.

**Comment by huykon** [comment]
still have problem when add a div container. anyone can help me resolved it?
