### ISSUE TITLE
Modal Dialog doesn't fade out

### ISSUE THREAD

**Issue by danielsd** [angular-ui/bootstrap#3633]
Under certain circumstances, the modal dialog will simply disappear instead of fading out (even though it successfully fades in).

The example in the documentation is what it should do (fade in and out).
https://angular-ui.github.io/bootstrap/#/modal

Ironically, the plunker link it generates shows the modal not properly fading out. I've saved my own to serve as an example here:
http://plnkr.co/edit/lmFTpQtfgV6qB4AuFrXj?p=preview
[*Edit from @chrisirhc to reduce confusion*: Please take note that the above Plunker does **not** include **angular-animate**. As such, no animations should be seen. This is a new requirement for animations, [see README](https://github.com/angular-ui/bootstrap#installation).]

I have the same issue in a separate project of mine where I am handling the modal differently but have the same bug. I can provide the 2nd example if it would help but I imagine the plunker should be enough.

The bug appears to be browser independent as it occurs both when I use Chrome v42.0.2311.135 m and in the developer edition of Firefox (39.0a2).

UPDATE: Note that the plnkr is using the latest version of angular-ui (0.13.0) and the latest supported version of angular (1.3.13). This is not about angular 1.4.

**Comment by karianna** [comment]
Is this on version 0.13.0?

**Comment by danielsd** [comment]
Yes

**Comment by RevanProdigalKnight** [comment]
+1 I can also confirm this issue.

**Comment by rvanbaalen** [comment]
Related: #3620

**Comment by xmlking** [comment]
also conforming the same issue with 0.13.0 + angular 1.4

**Comment by jondthompson** [comment]
Does anyone have a workaround for this bug? I really need to have it fixed by next week.

**Comment by CoenWarmer** [comment]
+1

**Comment by ntrifunovic** [comment]
+1

**Comment by alo** [comment]
@jondthompson you can set animation to false so it works while fixes.

**Comment by rvanbaalen** [comment]
Like I said did anyone here confirm everything is working as its supposed to when you include ngAnimate?

**Comment by neaped** [comment]
@rvanbaalen With ngAnimate 1.40 rc.2 the modal close successfully, but the animation effect (fade out / in) won't work.

**Comment by rvanbaalen** [comment]
Please test with versions that we actually support. UI Bootstrap supports Angular 1.3 so you should test with Angular 1.3 and ngAnimate 1.3

**Comment by neaped** [comment]
@rvanbaalen  UI Bootstrap with Angular 1.3 and ngAnimate 1.3 working fine :)

**Comment by rvanbaalen** [comment]
Thats what I mean. Everything else will be addressed soon when we implement Angular 1.4 compatibility (when the stable release is out).

**Comment by robertcasanova** [comment]
Hope this can help you, seems to be related to:
```
domEl.one('$animate:close', function closeFn() {
            $rootScope.$evalAsync(afterAnimating);
});
```
Seems that ```$animate:close``` is not triggered

**Comment by RobJacobs** [comment]
Comments from #3620

There is a known issue with Angular 1.4 and the Modal/Carousel directives. The ngAnimate module had some significant changes documented here that breaks how those directives are chaining animations. The area that needs to be addressed in the modal is here. As a workaround, I changed that line from:

    domEl.one('$animate:close', function closeFn() {
        $rootScope.$evalAsync(afterAnimating);
    }

To:

    $rootScope.$evalAsync(afterAnimating);

Keep in mind, you lose the closing animation.

**Comment by vprasanth** [comment]
Using 0.13.0 with angular 1.4 rc2, the modal dialog doesn't even appear for me. Just the dimmed backdrop.

**Comment by SlippySken** [comment]
Yay, I think angular 1.4.0 was release tonight :). When I close a dialog, the dialog disappears but the backdrop is still there.

**Comment by citosid** [comment]
@SlippySken I don't see the release on the official website, it is still on RC2. However, you can fix the issue as @RobJacobs mention. I did it in my code, and it is working now

**Comment by SlippySken** [comment]
I was looking at https://github.com/angular/angular.js/releases. It seems that the official website isn't updated yet. 
But the workaround is working :). Thanks :)

**Comment by rvanbaalen** [comment]
@vprasanth @SlippySken We dont officially support Angular 1.4 yet. UI Bootstrap 0.13.0 has full Angular 1.3 support however.

**Comment by Kepro** [comment]
+1

**Comment by ecsplendid** [comment]
+1

**Comment by rvanbaalen** [comment]
@ecsplendid We still don't support Angular 1.4 whether bower likes it or not. The official way to verify stable releases is going to www.angularjs.org and see what versions they are offering. Currently, AngularJS 1.4 is in a release candidate state.

Based on [this comment up here](https://github.com/angular-ui/bootstrap/issues/3633#issuecomment-102980690), I'm closing this issue. Someone can start a new issue that is specifically meant for Angular 1.4 support.

**Comment by danielsd** [comment]
Including the corresponding version of ngAnimate and including it in the module does fix the issue. However I don't see this dependency documented anywhere on UI Bootstrap.

If we are supposed to include ngAnimate in order to get UI Bootstrap to fully function, then at a minimum the dependency needs to be added to both the Plunkr and the documentation I linked to. Oddly enough, this doesn't explain how the live example in the documentation, which does not include ngAnimate, is still working. I am also of the opinion that the "Dependencies" section at the top of the git hub page needs to specify ngAnimate as module dependency in angular.

**Comment by rvanbaalen** [comment]
@danielsd I agree with you. The documentation needs an update and the dependency definition of the bower project needs that as well. If I'm not mistaken @RobJacobs fixed the dependency recently. If so, that will be tackled as soon as the next release lands.

Since all code (including the docs) is open source, please feel free to help us out on that one and send a PR that includes a better documentation regarding the dependencies. 

The plunkers need to be updated by @Foxandxss if I'm not mistaken.

**Comment by rvanbaalen** [comment]
By the way:

> If we are supposed to include ngAnimate in order to get UI Bootstrap to fully function, then at a minimum the dependency needs to be added to both the Plunkr and the documentation I linked to

ngAnimate is NOT required as a dependency. UI Bootstrap is fully functioning without it. ngAnimate only adds **optional** eye candy with animations. At least, that's how things are supposed to work.

**Comment by LeleDev** [comment]
Angular 1.4.0 has been released

**Comment by jberzins** [comment]
animation: false is workaround for me.

**Comment by johnculviner** [comment]
:+1:  on this issue. I'm going like this for now to globally fix it:
```
angular.module('MY_MODULE_NAME').config(function($modalProvider) {
  $modalProvider.options.animation = false;
});
```

**Comment by rhutchison** [comment]
http://angularjs.blogspot.com/2015/05/angular-140-jaracimrman-existence.html

**Comment by deeg** [comment]
Is there any update on this? Don't really want to have to turn animations off if possible.

I noticed this issue is labled with Angular 1.4 tag. The update in the top comment said it is for angular 1.3. I also have the issue on Angular 1.3.

**Comment by rvanbaalen** [comment]
I said this: 

> Please test with versions that we actually support. UI Bootstrap supports Angular 1.3 so you should test with Angular 1.3 and ngAnimate 1.3

And @neaped replied:

> UI Bootstrap with Angular 1.3 and ngAnimate 1.3 working fine :)

That's why it has a AngularJS 1.4 label. If you're experiencing this issue in 1.3 with UI Bootstrap 0.13, please create a plunkr that demonstrates your problem.

**Comment by RevanProdigalKnight** [comment]
It originally started out as an Angular 1.3 issue due to the sudden inclusion of the ngAnimate dependency, but people latched on top the Angular 1.4 issue because the ticket title didn't specify a version. The 1.4 stuff really should be in its own ticket and this one should be closed, but... \*shrugs\*

**Comment by pgkehle** [comment]
FWIW: As much as I'd hate to have to call this simple function for every modal I'd use, this does work and keeps animations:

          $('div.modal').removeClass('fade').addClass('hidden');
          $('body').removeClass('modal-open');
          $('.modal-backdrop').remove();

**Comment by elado** [comment]
Another workaround:

```coffee
instance = $modal.open(options)
promise = instance.result
promise.finally ->
  $timeout ->
    $('.modal:last').trigger('$animate:close')
    $timeout ->
      $('.modal-backdrop:last').trigger('$animate:close')
```

it doesn't show closing animation but it's not too hard to add.

**Comment by philBrown** [comment]
@pgkehle, @elado should probably note that both of your solutions require jQuery.

**Comment by rvanbaalen** [comment]
One of the main aims of UI Bootstrap is to prevent the need of jQuery in your project. So that kind of defeats the purpose :wink:

**Comment by Oceanswave** [comment]
+1

**Comment by walane** [comment]
Hi,

Do you know when an update will be available?

Thank you for your work :)

**Comment by frapontillo** [comment]
:+1:, same issues, waiting for 0.14.0.

**Comment by LeonanCarvalho** [comment]
+1 

Take a look on https://docs.angularjs.org/guide/migration "Migrating from 1.3 to 1.4"

Animation-related callbacks are now fired on $animate.on instead of directly being on the element.
```javascript
// < 1.4
element.on('$animate:before', function(e, data) {
  if (data.event === 'enter') { ... }
});
element.off('$animate:before', fn);

// 1.4+
$animate.on(element, 'enter', function(data) {
  //...
});
$animate.off(element, 'enter', fn);
```
The function params for $animate.enabled() when an element is used are now flipped. This fix allows the function to act as a getter when a single element param is provided.
```javascript
// < 1.4
$animate.enabled(false, element);

// 1.4+
$animate.enabled(element, false);
```
In addition to disabling the children of the element, $animate.enabled(element, false) will now also disable animations on the element itself.

There is no need to call $scope.$apply or $scope.$digest inside of a animation promise callback anymore since the promise is resolved within a digest automatically. (Not to worry, any extra digests will not be run unless the promise is used.)

```javascript
// < 1.4
$animate.enter(element).then(function() {
  $scope.$apply(function() {
    $scope.explode = true;
  });
});

// 1.4+
$animate.enter(element).then(function() {
  $scope.explode = true;
});
```
When an enter, leave or move animation is triggered then it will always end any pending or active parent class based animations (animations triggered via ngClass) in order to ensure that any CSS styles are resolved in time.

**Comment by YidingW** [comment]
+1 Thanks @LeonanCarvalho for the information

**Comment by warapitiya** [comment]
Any fix for this rather than setting
```javascript
animation: false
```

**Comment by 311chaos** [comment]
I also have this issue with angular 1.3. Modals open, but will not close. I have been able to get around this by disabling animations globally, however this is not desirable.

I am confused though, I have seen animations working on Plunker with 1.3 and 0.13.0, however there seems to be a good portion of people who are seeing this issue. It seems that something else is involved.

**Comment by astreate** [comment]
I'm experiencing the same issue with angular 1.3.15, angular-animate 1.3.15, and ui-bootstrap 0.13.0.  I am unable to close a modal after opening it.

**Comment by LeonanCarvalho** [comment]
What about just CSS animation?

**Comment by esion** [comment]
@311chaos @astreate I've no problem with backdrop on angular 1.3 since it requires ngAnimate. 

Here is the plnkr http://plnkr.co/edit/zHEHNTI1Yps7UBh9Cze9?p=preview

**Comment by Janjuks** [comment]
+1 @astreate . Also unable to close modal with those same versions.

**Comment by esion** [comment]
Hi, I've started a PR. there are still things hardcoded but it works. Any reviews would be appreciated : https://github.com/esion/bootstrap/pull/1 this include a demo

**Comment by mcianc** [comment]
I have the same issue, 0.13 with angular grater than 1.3.16 does not work

**Comment by tuckerjt07** [comment]
This is what I am using as a workaround.

<div class="modal-footer">
        <button class="btn btn-primary"
                ng-click="registerModal.ok()"
                remove-modal>OK</button>
        <button class="btn btn-warning"
                ng-click="registerModal.cancel()"
                remove-modal>Cancel</button>
</div>

/*global angular */
(function () {
    'use strict';
    angular.module('CorvetteClub.removemodal.directive', [])
        .directive('removeModal', ['$document', function ($document) {
            return {
                restrict: 'A',
                link: function (scope, element, attrs) {
                    element.bind('click', function () {
                        $document[0].body.classList.remove('modal-open');
                        angular.element($document[0].getElementsByClassName('modal-backdrop')).remove();
                        angular.element($document[0].getElementsByClassName('modal')).remove();
                    });
                }
            };
        }]);
}());

**Comment by chrisirhc** [comment]
Note that the original bug/issue here is actually that the modal initially fades in when it should instead skip the animation since `ngAnimate` module wasn't included.

**Comment by tuckerjt07** [comment]
@chrisirhc No, the original issue was that the modal would fade in correctly but would skip the fade out animation and just disappear.

**Comment by chrisirhc** [comment]
That's incorrect. If angular-animate isn't included, there expected behavior is that there will be no animations at all. Disappearing is the expected behavior. You need angular-animate for animations, that's the change when upgrading to 0.13 .

**Comment by tuckerjt07** [comment]
Read the first sentence in the OP

[Quote="danielsd"]
Under certain circumstances, the modal dialog will simply disappear instead of fading out (even though it successfully fades in).
[/Quote]

**Comment by chrisirhc** [comment]
Yes, successfully fading in is the *wrong* behavior.

**Comment by tuckerjt07** [comment]
That's not what is being discussed at all. The entire gist of the thread from the original OP to the very end has been a series of workarounds to determine how to keep the animations but also not include breaking changes by doing so.

I'm not trying to turn this into an argument but incorrectly stating the issue does nothing to help resolve it.

**Comment by chrisirhc** [comment]
The first thing you need for animations is angular-animate . If it isn't included, the discussion is on the wrong track.

**Comment by tuckerjt07** [comment]
Correct, and that was mentioned, and resolved, early on in the thread. Now the issue is that with the changes made to ngAnimate the actions provided by $modal and $modalInstance are not firing the necessary functions to remove all of the classes provided by $modal. In my case it made the entire screen disabled irregardless of if there was a mask or not. 

The issue has nothing to do with inclusion at this point. Now what needs to be done is that the code needs to be updated to work with ngAnimate in its newer state. Until then a workaround is what will need to be used and has been provided.

**Comment by chrisirhc** [comment]
Please see if #3895 resolves your issue. Otherwise, please open another issue for that discussion.
The reason for this is so that the issue doesn't get lost in the haystack. If the discussion is no longer about the original issue, it will be missed by the maintainer.

Unfortunately, as a maintainer, I have limited amount of time to go through issues every day and unable to go through every single message or track down every fork in the discussion.

I think the fact that the original issue was resolved is good reason to close this. This issue in its current state only serves to confuse others.

**Comment by tuckerjt07** [comment]
This thread needs to be forked into a completely new issue about five posts from the top if the focus is going to be put on inclusion as most of the discussion is not pertinent in that vein.

**Comment by dyatchenko** [comment]
I found out that the problem is in [0.13.0][1] version. [0.12.0][2] works fine even with AngularJS 1.4.1.

   [1]: http://plnkr.co/edit/RtjZY9eBDPkotMyn4GsU?p=preview
   [2]: http://plnkr.co/edit/RtjZY9eBDPkotMyn4GsU?p=preview

**Comment by LunarDevelopment** [comment]
:+1: 

Can this fix be rolled out to bower asap please?

**Comment by LeleDev** [comment]
+1

**Comment by iksose** [comment]
@dyatchenko Thanks, works for me

**Comment by LunarDevelopment** [comment]
BRAVO. Thanks for the speedy fix!

**Comment by dbarabander** [comment]
+1 @dyatchenko

**Comment by rsfurlan90** [comment]
Thanks @dyatchenko 

Version 0.12.1 also works fine using latest Angular (1.4.1)

**Comment by LeleDev** [comment]
@rsfurlan90 yes, this is the paradox

**Comment by raphael22** [comment]
But popover-template while only works with 0.13.0 in Angular 1.4

**Comment by C00per** [comment]
I'm confused... So the only way to solve this problem is using  0.12.1 with Angular 1.4?

**Comment by raphael22** [comment]
Or config animation to false in 0.13.0
```$modalProvider.options.animation = false;```

**Comment by chrisirhc** [comment]
This should be fixed on master and via next release (0.13.1).

**Comment by bennettatoms** [comment]
Downloaded 0.13.1 today, but the issue with the modal background not closing when animations are enabled remains (I'm using Angular 1.4.2).

**Comment by LeleDev** [comment]
@bennettatoms 
It seems fixed for me on angular 1.4.2 (with ng-animate installed), but I had to set ```$modalProvider.options.animation = true;``` in order to show animations (are they off by default now?)

**Comment by aaaaahaaaaa** [comment]
Still experiencing the same problem with 0.13.1 and Angular 1.4.3

**Comment by raphael22** [comment]
1.4.3 & 0.13.1 here, no more problem for me. neither with popover-template.

**Comment by aaaaahaaaaa** [comment]
Double checked. I confirm the problem is there on my application with 0.13.1. Works if i rollback to 0.12.1. I'll try to investigate what could be the problem a bit later if I have the time.

**Comment by bartread** [comment]
Fixed for me too with Angular 1.4.3 and Angular-Bootstrap 0.13.1.

**Comment by EmersonMellado** [comment]
I'm using a workaround solution by turning off the animation.

$modal.open({
     animation: false
}

Att,
Emerson R. Mellado

2015-07-29 12:34 GMT-03:00 aaaaahaaaaa <notifications@github.com>:

**Comment by mpiasta-ca** [comment]
Still broken, right? Using angular-bootstrap 0.13.1 (bower) and angular 1.4.2.

**Comment by mpiasta-ca** [comment]
Success! Doesn't work with angular 1.4.2 with angular-bootstrap 0.13.1, but when upgraded to angular 1.4.3, suddenly starts to work.

But one thing I do not like is: when modal is closing, first the .modal-dialog will animate-out; and only when it is complete, then the .modal-backdrop will begin animate-out. So if .modal-dialog animation duration is 250ms, and .modal-backdrop animation is 250ms, it will take 500ms for the modal to close.

However, when opening modal, .modal-dialog and .modal-backdrop animate simultaneously. So it each requires duration of 250ms, the modal will use 250ms to open. 

As someone who does not like waiting, I find this to be irksome. However, if I reduce the animation-out duration to be 125ms each, for a total of 250ms, the animation feels choppy and unfulfilling.

**Comment by astreate** [comment]
This appears to be working now with angular 1.4.3 and angular-bootstrap 0.13.1.

**Comment by Droritos** [comment]
Confirm v1.4.3, v0.13.1

**Comment by levin81** [comment]
Using 1.43 with 0.13.1 with Bootstrap 3.3.5, fading in works but fading out doesn't work. It is due to reaching ``domEl.remove()`` in ``afterAnimating()`` too fast which removes the element before it has finished fading out.

**Comment by Rems69** [comment]
I had the same issue @levin81, try to include ngAnimate module, it worked for me.

**Comment by levin81** [comment]
I have included it. I have tried messing around with different versions of Angular as well. Still doesn't work.

**Comment by ken945** [comment]
I updated angularJs 1.4.3 & angular-ui 0.13.2 from Nugget in Visual Studio 2012 yesterday,
the modal option animate is true, and no matter nganimate is included or not, modal just fade in no fade out. any workaround? I am still stocked in this animation....

**Comment by levin81** [comment]
Look at the plunker that I linked - it is barebones. Did you add 'ngAnimate' to the dependencies of your app?

**Comment by itsazzad** [comment]
not working with me with v1.4.3, v0.13.1. All links become disabled after the modal dismissal.
Disabling animation have solved the issue.
```animate: false```

**Comment by bhushanvaidya3** [comment]
Thanks @itsazzad . I've disabled the animation for now as well.

**Comment by gbukauskas** [comment]
Add property 'animation: false' for resolving this issue:
            var modalInstance = $modal.open({
                templateUrl: '...',
                controller: myController,
                animation: false,
                size: 'lg',
                resolve: {
                    ...
                }
            });

**Comment by bozydar** [comment]
I debugged function ```removeAfterAnimate``` and it looks like the problem with the fade out is caused by this one: https://github.com/angular/angular.js/issues/6049

**Comment by MrOutput** [comment]
+1

**Comment by Propaganistas** [comment]
As @Rems69 mentioned: including ngAnimate fixed this problem for me as well.

**Comment by henriqueprj** [comment]
updating to angular-bootstrap 0.13.3 solved the problem for me too.

**Comment by Alttaf** [comment]
updating to angular-bootstrap 0.13.3 solved the problem for me too.

**Comment by arekzelechowski** [comment]
The bug still exist in my setup (ng 1.4.8). Downgrading to 0.12.1 fixes problem.
