### ISSUE TITLE
Popover and Tooltip positioning issues

### ISSUE THREAD

**Issue by kruser** [angular-ui/bootstrap#4421]
We recently upgraded to angular, angular-bootstrap and bootstrap and since have had popover/tooltip placement issues.

Installed
```json
  "dependencies": {
    "angular": "~1.4.4",
    "angular-resource": "~1.4.4",
    "angular-cookies": "~1.4.4",
    "angular-sanitize": "~1.4.4",
    "angular-route": "~1.4.4",
    "angular-cookie": "~4.0.0",
    "angular-bootstrap": "~0.13.3",
    "angular-touch": "~1.4.4",
    "angular-local-storage": "~0.1.4",
    "moment": "~2.7.0",
    "mathjs": "~0.25.0",
    "angular-bindonce": "~0.3.3",
    "moment-timezone": "~0.2.2",
    "underscore": "~1.7.0",
    "ngInfiniteScroll": "~1.2.0",
    "d3": "~3.5.0",
    "d3-tip": "~0.6.7"
  }
```

Popovers were suddenly shown at 0,0 for a split second before being positioned where they needed to be. Something similar is happening with tooltips, though not at 0,0.

I had to redact nearly everything here but hopefully you get the gist. This was taken from a screencast as the problem occurs just for maybe a few hundred ms before being positioned correctly.
![image](https://cloud.githubusercontent.com/assets/2208700/9891349/4aca369c-5bcb-11e5-85f7-a9ef3e13ef50.png)

We're usually using ```popover-append-to-dom="true"``` and ```popover-trigger="mouseenter"``` (same for tooltips).

Has anybody run into this issue? If so, any workarounds?

**Comment by icfantv** [comment]
@kruser, this is fixed in `master`.

**Comment by kruser** [comment]
Ok, thanks @icfantv. Let me know if there is an imminent release coming that would include this. I don't see anything on the milestones.

**Comment by icfantv** [comment]
I think it's going to be a while.  There's a lot of stuff going into 0.14.0 and as of now, there's no plan to do a 0.13.5 release.

You basically have three options:  1) go back to 0.13.3, 2) build and use the 0.13.4-SNAPSHOT release, or 3) patch the 0.13.3 release with the fix you need.

I realize none of these are ideal and while we try to keep the SNAPSHOT builds stable, there's no guarantee that something won't slip in.  Thus, I think the lesser of all the evils would be option 3.

**Comment by kruser** [comment]
I built a snapshot and confirmed this is fixed. But the only reason I'm on 13.x is for templates inside popovers but I'm having another issue with that. I'll open a separate thread for that. Thanks again, appreciate the responses.

**Comment by kruser** [comment]
Does popover require this fix too? I'm still seeing the issue there.
